[PHP]
memory_limit        = 512M
upload_max_filesize = 32M
post_max_size       = 32M
max_execution_time  = 60
display_errors      = On
error_reporting     = E_ALL

[Date]
date.timezone = Europe/Warsaw

[opcache]
opcache.enable     = 0
opcache.enable_cli = 0
